insert into glossary values('abstract method', 'One with only a signature and no implementation body.');
insert into glossary values('abstraction', 'Creating an abstract concept-object by keeping common features to various concrete objects/systems of study.');
insert into glossary values('agent architecture', 'A blueprint for software agents and intelligent control systems depicting the arrangement of components.');
insert into glossary values('agent-based model (ABM)', 'A class of computational models for simulating the actions and interactions of autonomous agents with a view to assessing the effects on the system as a whole.');
insert into glossary values('aggregate function', 'In database management, a function in which the values of multiple rows are grouped to form a single value, such as a sum or max.');
insert into glossary values('agile software development', 'An approach to software development under which and solutions evolve through self-organizing and cross-functional teams');
insert into glossary values('algorithm', 'An unambiguous specification of how to solve a class of problems.');
insert into glossary values('algorithm design', 'A method or mathematical process for problem-solving and for engineering algorithms.');
insert into glossary values('algorithmic efficiency', 'A property of an algorithm which relates to the number of computational resources used by the algorithm.');
insert into glossary values('American Standard Code for Information Interchange (ASCII)', 'A character encoding standard for electronic communications.');
insert into glossary values('application programming interface (API)', 'A set of subroutine definitions, communication protocols, and tools for building software.');
insert into glossary values('application software', 'Computer software designed to perform a group of coordinated functions, tasks, or activities for the benefit of the user.');
insert into glossary values('array data structure', 'A data structure consisting of a collection of elements, each identified by at least one array index or key');
insert into glossary values('artifact', 'One of many kinds of tangible by-products produced during the development of software.');
insert into glossary values('artificial intelligence (AI)', 'Intelligence demonstrated by machines.');
insert into glossary values('assertion', 'In programming, a statement that a predicate is always true at that point in code execution');
insert into glossary values('associative array', 'abstract data type composed of a collection of (key, value) pairs. Each possible key appears at most once.');
insert into glossary values('automata theory', 'The study of abstract machines and automata, as well as the computational problems that can be solved using them.');
insert into glossary values('automated reasoning', 'An area of computer science and mathematical logic dedicated to understanding different aspects of reasoning.');

insert into glossary values('bandwidth', 'The maximum rate of data transfer across a given path.');
insert into glossary values('Bayesian programming', 'a technique to solve problems when less than the necessary information is available.');
insert into glossary values('benchmark', 'Running a computer program(s), or other operations, in order to assess the performance of an object');
insert into glossary values('best, worst and average case', 'Expressions of what the resource usage is at least, at most, and on average, respectively, for a given algorithm.');
insert into glossary values('big data', 'Data sets that are too large or complex for traditional data-processing application software to adequately deal with.');
insert into glossary values('big O notation', 'A notation that describes the limiting behavior of a function when the argument tends towards a particular value/infinity.');
insert into glossary values('binary number', 'A number expressed in the base-2 numeral system.');
insert into glossary values('binary search algorithm', 'A search algorithm that finds the position of a target value within a sorted array.');
insert into glossary values('binary tree', 'A tree data structure in which each node has at most two children.');
insert into glossary values('bioinformatics', 'An interdisciplinary field that combines biology, computer science, information engineering, mathematics, and statistics.');
insert into glossary values('bit', 'A basic unit of information used in computing and digital communications.');
insert into glossary values('bit rate (R)', 'The number of bits that are conveyed or processed per unit of time.');
insert into glossary values('blacklist', 'An access control mechanism that allows through all elements, except those explicitly mentioned in a list of prohibited elements.');
insert into glossary values('BMP file format', 'A raster graphics image file format used to store bitmap digital images independently of the display device.');
insert into glossary values('Boolean data type', 'A data type that has one of two possible values (usually denoted true and false)');
insert into glossary values('Boolean expression', 'An expression used in a programming language that returns a Boolean value when evaluated.');
insert into glossary values('Boolean algebra', 'The branch of algebra in which the values of the variables are the truth values');
insert into glossary values('byte', 'A unit of digital information that most commonly consists of eight bits, representing a binary number.');
insert into glossary values('booting', 'The procedures implemented in starting up a computer or computer appliance until it can be used.');

insert into glossary values('callback', 'Any executable code that is passed as an argument to other code that is expected to execute the argument at a given time.');
insert into glossary values('central processing unit (CPU)', 'The electronic circuitry within a computer that carries out the instructions of a computer program.');
insert into glossary values('character', 'A unit of information that roughly corresponds to a grapheme, grapheme-like unit, or symbol');
insert into glossary values('cipher', 'An algorithm for performing encryption or decryption.');
insert into glossary values('class', 'An extensible program-code-template for creating objects, providing implementations of behavior');
insert into glossary values('class-based programming', 'A style of object-oriented programming which inheritance occurs via defining "classes" of objects');
insert into glossary values('client', 'A piece of computer hardware or software that accesses a service made available by a server.');
insert into glossary values('cleanroom software engineering', 'A software development process intended to produce software with a certifiable level of reliability.');
insert into glossary values('closure', 'A technique for implementing lexically scoped name binding in a language with first-class functions.');
insert into glossary values('cloud computing', 'Shared pools of configurable computer system resources that can be rapidly provisioned with minimal management effort.');
insert into glossary values('code library', 'A collection of non-volatile resources used by computer programs, often for software development.');
insert into glossary values('coding', 'The process of designing and building an executable computer program for accomplishing a specific computing task.');
insert into glossary values('coding theory', 'The study of the properties of codes and their respective fitness for specific applications.');
insert into glossary values('cognitive science', 'The interdisciplinary, scientific study of the mind and its processes.);
insert into glossary values('collection', 'Some number of data items that have some shared significance to the problem being solved');
insert into glossary values('comma-separated values (CSV)', 'A delimited text file that uses a comma to separate values.');
insert into glossary values('compiler', 'A computer program that transforms code written in one programming language into another');
insert into glossary values('computability theory', 'The study of computable functions, Turing degrees,generalized computability and definability.');
insert into glossary values('computation', 'A calculation that includes both arithmetical and non-arithmetical steps and follows a well-defined model.');
insert into glossary values('computational biology', 'Involves computational simulation techniques to the study of biological, ecological, behavioural, and social systems.');
insert into glossary values('computational chemistry', 'A branch of chemistry that uses computer simulation to assist in solving chemical problems.');
insert into glossary values('computational complexity theory', 'algorithm design definition');
insert into glossary values('computational model', 'algorithm design definition');
insert into glossary values('computational neuroscience', 'algorithm design definition');
insert into glossary values('computational physics', 'algorithm design definition');
insert into glossary values('computational science', 'algorithm design definition');
insert into glossary values('computational steering', 'algorithm design definition');
insert into glossary values('computer', 'algorithm design definition');
insert into glossary values('computer architecture', 'algorithm design definition');
insert into glossary values('computer data storage', 'algorithm design definition');
insert into glossary values('computer ethics', 'algorithm design definition');
insert into glossary values('computer graphics', 'algorithm design definition');
insert into glossary values('computer network', 'algorithm design definition');
insert into glossary values('computer program', 'algorithm design definition');
insert into glossary values('computer programming', 'algorithm design definition');
insert into glossary values('computer science', 'algorithm design definition');
insert into glossary values('computer scientist', 'algorithm design definition');
insert into glossary values('computer security', 'algorithm design definition');
insert into glossary values('computer vision', 'algorithm design definition');
insert into glossary values('computing', 'algorithm design definition');
insert into glossary values('concatenation', 'algorithm design definition');
insert into glossary values('concurrency', 'algorithm design definition');
insert into glossary values('conditional', 'algorithm design definition');
insert into glossary values('container', 'algorithm design definition');
insert into glossary values('continuation-passing style (CPS)', 'algorithm design definition');
insert into glossary values('control flow', 'algorithm design definition');
insert into glossary values('Creative Commons (CC)', 'algorithm design definition');
insert into glossary values('cryptography', 'algorithm design definition');
insert into glossary values('CSV', 'algorithm design definition');
insert into glossary values('cyberbullying', 'algorithm design definition');
insert into glossary values('cyberspace', 'algorithm design definition');

insert into glossary values('daemon', 'algorithm design definition');
insert into glossary values('data center', 'algorithm design definition');
insert into glossary values('database', 'algorithm design definition');
insert into glossary values('data mining', 'algorithm design definition');
insert into glossary values('data science', 'algorithm design definition');
insert into glossary values('data structure', 'algorithm design definition');
insert into glossary values('data type', 'algorithm design definition');
insert into glossary values('debugging', 'algorithm design definition');
insert into glossary values('declaration', 'algorithm design definition');
insert into glossary values('digital data', 'algorithm design definition');
insert into glossary values('digital signal processing (DSP)', 'algorithm design definition');
insert into glossary values('discrete event simulation (DES)', 'algorithm design definition');
insert into glossary values('disk storage', 'algorithm design definition');
insert into glossary values('distributed computing', 'algorithm design definition');
insert into glossary values('divide and conquer algorithm', 'algorithm design definition');
insert into glossary values('documentation', 'algorithm design definition');
insert into glossary values('domain', 'algorithm design definition');
insert into glossary values('Domain Name System (DNS)', 'algorithm design definition');
insert into glossary values('double-precision floating-point format', 'algorithm design definition');
insert into glossary values('download', 'algorithm design definition');

insert into glossary values('edge device', 'algorithm design definition');
insert into glossary values('encryption', 'algorithm design definition');
insert into glossary values('event', 'algorithm design definition');
insert into glossary values('event-driven programming', 'algorithm design definition');
insert into glossary values('evolutionary computing', 'algorithm design definition');
insert into glossary values('executable', 'algorithm design definition');
insert into glossary values('execution', 'algorithm design definition');
insert into glossary values('exception handling', 'algorithm design definition');
insert into glossary values('expression', 'algorithm design definition');

insert into glossary values('fault-tolerant computer system', 'algorithm design definition');
insert into glossary values('feasibility study', 'algorithm design definition');
insert into glossary values('field', 'algorithm design definition');
insert into glossary values('filename extension', 'algorithm design definition');
insert into glossary values('filter (software)', 'algorithm design definition');
insert into glossary values('floating point arithmetic', 'algorithm design definition');
insert into glossary values('for loop', 'algorithm design definition');
insert into glossary values('formal methods', 'algorithm design definition');
insert into glossary values('formal verification', 'algorithm design definition');
insert into glossary values('functional programming', 'algorithm design definition');

insert into glossary values('game theory', 'algorithm design definition');
insert into glossary values('garbage in, garbage out (GIGO)', 'algorithm design definition');
insert into glossary values('gigabyte', 'algorithm design definition');
insert into glossary values('global variable', 'algorithm design definition');
insert into glossary values('graph theory', 'algorithm design definition');

insert into glossary values('handle', 'algorithm design definition');
insert into glossary values('hard problem', 'algorithm design definition');
insert into glossary values('hash function', 'algorithm design definition');
insert into glossary values('hash table', 'algorithm design definition');
insert into glossary values('heap', 'algorithm design definition');
insert into glossary values('heapsort', 'algorithm design definition');
insert into glossary values('human-computer interaction (HCI)', 'algorithm design definition');

insert into glossary values('identifier', 'algorithm design definition');
insert into glossary values('IDE', 'algorithm design definition');
insert into glossary values('imperative programming', 'algorithm design definition');
insert into glossary values('incremental build model', 'algorithm design definition');
insert into glossary values('information space analysis', 'algorithm design definition');
insert into glossary values('inheritance', 'algorithm design definition');
insert into glossary values('input/output (I/O)', 'algorithm design definition');
insert into glossary values('insertion sort', 'algorithm design definition');
insert into glossary values('instruction cycle', 'algorithm design definition');
insert into glossary values('integer', 'algorithm design definition');
insert into glossary values('integrated development environment (IDE)', 'algorithm design definition');
insert into glossary values('integration testing', 'algorithm design definition');
insert into glossary values('intellectual property (IP)', 'algorithm design definition');
insert into glossary values('intelligent agent', 'algorithm design definition');
insert into glossary values('interface', 'algorithm design definition');
insert into glossary values('internal documentation', 'algorithm design definition');
insert into glossary values('internet', 'algorithm design definition');
insert into glossary values('internet bot', 'algorithm design definition');
insert into glossary values('interpreter', 'algorithm design definition');
insert into glossary values('invariant', 'algorithm design definition');
insert into glossary values('iteration', 'algorithm design definition');

insert into glossary values('Java', 'algorithm design definition');

insert into glossary values('kernel', 'algorithm design definition');

insert into glossary values('library (computing)', 'algorithm design definition');
insert into glossary values('linear search', 'algorithm design definition');
insert into glossary values('linked list', 'algorithm design definition');
insert into glossary values('linker', 'algorithm design definition');
insert into glossary values('list', 'algorithm design definition');
insert into glossary values('loader', 'algorithm design definition');
insert into glossary values('logic error', 'algorithm design definition');
insert into glossary values('logic programming', 'algorithm design definition');

insert into glossary values('machine learning (ML)', 'algorithm design definition');
insert into glossary values('machine vision (MV)', 'algorithm design definition');
insert into glossary values('mathematical logic', 'algorithm design definition');
insert into glossary values('matrix', 'algorithm design definition');
insert into glossary values('memory', 'algorithm design definition');
insert into glossary values('merge sort', 'algorithm design definition');
insert into glossary values('method', 'algorithm design definition');
insert into glossary values('methodology', 'algorithm design definition');
insert into glossary values('modem', 'algorithm design definition');

insert into glossary values('natural language processing (NLP)', 'algorithm design definition');
insert into glossary values('node', 'algorithm design definition');
insert into glossary values('number theory', 'algorithm design definition');
insert into glossary values('numerical analysis', 'algorithm design definition');
insert into glossary values('numerical method', 'algorithm design definition');

insert into glossary values('object', 'algorithm design definition');
insert into glossary values('object code', 'algorithm design definition');
insert into glossary values('object-oriented analysis and design (OOAD)', 'algorithm design definition');
insert into glossary values('object-oriented programming (OOP)', 'algorithm design definition');
insert into glossary values('open-source software (OSS)', 'algorithm design definition');
insert into glossary values('operating system (OS)', 'algorithm design definition');
insert into glossary values('optical fiber', 'algorithm design definition');

insert into glossary values('pair programming', 'algorithm design definition');
insert into glossary values('parallel computing', 'algorithm design definition');
insert into glossary values('parameter', 'algorithm design definition');
insert into glossary values('peripheral', 'algorithm design definition');
insert into glossary values('pointer', 'algorithm design definition');
insert into glossary values('postcondition', 'algorithm design definition');
insert into glossary values('precondition', 'algorithm design definition');
insert into glossary values('primary storage', 'algorithm design definition');
insert into glossary values('priority queue', 'algorithm design definition');
insert into glossary values('primitive data type', 'algorithm design definition');
insert into glossary values('procedural programming', 'algorithm design definition');
insert into glossary values('procedure', 'algorithm design definition');
insert into glossary values('program lifecycle phase', 'algorithm design definition');
insert into glossary values('programming language', 'algorithm design definition');
insert into glossary values('programming language implementation', 'algorithm design definition');
insert into glossary values('programming language theory', 'algorithm design definition');
insert into glossary values('Prolog', 'algorithm design definition');
insert into glossary values('Python', 'algorithm design definition');

insert into glossary values('quantum computing', 'algorithm design definition');
insert into glossary values('queue', 'algorithm design definition');
insert into glossary values('quicksort', 'algorithm design definition');

insert into glossary values('R programming language', 'algorithm design definition');
insert into glossary values('radix', 'algorithm design definition');
insert into glossary values('record', 'algorithm design definition');
insert into glossary values('recursion', 'algorithm design definition');
insert into glossary values('reference', 'algorithm design definition');
insert into glossary values('reference counting', 'algorithm design definition');
insert into glossary values('relational database', 'algorithm design definition');
insert into glossary values('reliability engineering', 'algorithm design definition');
insert into glossary values('regression testing', 'algorithm design definition');
insert into glossary values('requirements analysis', 'algorithm design definition');
insert into glossary values('robotics', 'algorithm design definition');
insert into glossary values('round-off error', 'algorithm design definition');
insert into glossary values('router', 'algorithm design definition');
insert into glossary values('routing table', 'algorithm design definition');
insert into glossary values('run time', 'algorithm design definition');
insert into glossary values('run time error', 'algorithm design definition');

insert into glossary values('search algorithm', 'algorithm design definition');
insert into glossary values('secondary storage', 'algorithm design definition');
insert into glossary values('selection sort', 'algorithm design definition');
insert into glossary values('semantics', 'algorithm design definition');
insert into glossary values('sequence', 'algorithm design definition');
insert into glossary values('serializability', 'algorithm design definition');
insert into glossary values('serialization', 'algorithm design definition');
insert into glossary values('service level agreement', 'algorithm design definition');
insert into glossary values('set', 'algorithm design definition');
insert into glossary values('singleton variable', 'algorithm design definition');
insert into glossary values('software', 'algorithm design definition');
insert into glossary values('software agent', 'algorithm design definition');
insert into glossary values('software construction', 'algorithm design definition');
insert into glossary values('software deployment', 'algorithm design definition');
insert into glossary values('software design', 'algorithm design definition');
insert into glossary values('software development', 'algorithm design definition');
insert into glossary values('software development process', 'algorithm design definition');
insert into glossary values('software engineering', 'algorithm design definition');
insert into glossary values('software maintenance', 'algorithm design definition');
insert into glossary values('software prototyping', 'algorithm design definition');
insert into glossary values('software requirements specification', 'algorithm design definition');
insert into glossary values('software testing', 'algorithm design definition');
insert into glossary values('sorting algorithm', 'algorithm design definition');
insert into glossary values('source code', 'algorithm design definition');
insert into glossary values('spiral model', 'algorithm design definition');
insert into glossary values('stack', 'algorithm design definition');
insert into glossary values('state', 'algorithm design definition');
insert into glossary values('statement', 'algorithm design definition');
insert into glossary values('storage', 'algorithm design definition');
insert into glossary values('stream', 'algorithm design definition');
insert into glossary values('string', 'algorithm design definition');
insert into glossary values('structured storage', 'algorithm design definition');
insert into glossary values('subroutine', 'algorithm design definition');
insert into glossary values('symbolic computation', 'algorithm design definition');
insert into glossary values('syntax', 'algorithm design definition');
insert into glossary values('syntax error', 'algorithm design definition');
insert into glossary values('system console', 'algorithm design definition');

insert into glossary values('technical documentation', 'algorithm design definition');
insert into glossary values('third-generation programming language', 'algorithm design definition');
insert into glossary values('top-down and bottom-up design', 'algorithm design definition');
insert into glossary values('tree', 'algorithm design definition');
insert into glossary values('type theory', 'algorithm design definition');

insert into glossary values('upload', 'algorithm design definition');
insert into glossary values('Uniform Resource Locator (URL)', 'algorithm design definition');
insert into glossary values('user', 'algorithm design definition');
insert into glossary values('user agent', 'algorithm design definition');
insert into glossary values('user interface (UI)', 'algorithm design definition');
insert into glossary values('user interface design', 'algorithm design definition');

insert into glossary values('variable', 'algorithm design definition');
insert into glossary values('virtual machine (VM)', 'algorithm design definition');
insert into glossary values('V-Model', 'algorithm design definition');

insert into glossary values('waterfall model', 'algorithm design definition');
insert into glossary values('Waveform Aartifactudio File Format', 'algorithm design definition');
insert into glossary values('web crawler', 'algorithm design definition');
insert into glossary values('Wi-Fi', 'algorithm design definition');

insert into glossary values('XHTML', 'algorithm design definition');
