insert into glossary values('abstract method', 'One with only a signature and no implementation body.');
insert into glossary values('abstraction', 'Creating an abstract concept-object by keeping common features to various concrete objects/systems of study.');
insert into glossary values('agent architecture', 'A blueprint for software agents and intelligent control systems depicting the arrangement of components.');
insert into glossary values('agent-based model (ABM)', 'A class of computational models for simulating the actions and interactions of autonomous agents with a view to assessing the effects on the system as a whole.');
insert into glossary values('aggregate function', 'In database management, a function in which the values of multiple rows are grouped to form a single value, such as a sum or max.');
insert into glossary values('agile software development', 'An approach to software development under which and solutions evolve through self-organizing and cross-functional teams');
insert into glossary values('algorithm', 'An unambiguous specification of how to solve a class of problems.');
insert into glossary values('algorithm design', 'A method or mathematical process for problem-solving and for engineering algorithms.');
insert into glossary values('algorithmic efficiency', 'A property of an algorithm which relates to the number of computational resources used by the algorithm.');
insert into glossary values('American Standard Code for Information Interchange (ASCII)', 'A character encoding standard for electronic communications.');
insert into glossary values('application programming interface (API)', 'A set of subroutine definitions, communication protocols, and tools for building software.');
insert into glossary values('application software', 'Computer software designed to perform a group of coordinated functions, tasks, or activities for the benefit of the user.');
insert into glossary values('array data structure', 'A data structure consisting of a collection of elements, each identified by at least one array index or key');
insert into glossary values('artifact', 'One of many kinds of tangible by-products produced during the development of software.');
insert into glossary values('artificial intelligence (AI)', 'Intelligence demonstrated by machines.');
insert into glossary values('assertion', 'In programming, a statement that a predicate is always true at that point in code execution');
insert into glossary values('associative array', 'abstract data type composed of a collection of (key, value) pairs. Each possible key appears at most once.');
insert into glossary values('automata theory', 'The study of abstract machines and automata, as well as the computational problems that can be solved using them.');
insert into glossary values('automated reasoning', 'An area of computer science and mathematical logic dedicated to understanding different aspects of reasoning.');

insert into glossary values('bandwidth', 'The maximum rate of data transfer across a given path.');
insert into glossary values('Bayesian programming', 'a technique to solve problems when less than the necessary information is available.');
insert into glossary values('benchmark', 'Running a computer program(s), or other operations, in order to assess the performance of an object');
insert into glossary values('best, worst and average case', 'Expressions of what the resource usage is at least, at most, and on average, respectively, for a given algorithm.');
insert into glossary values('big data', 'Data sets that are too large or complex for traditional data-processing application software to adequately deal with.');
insert into glossary values('big O notation', 'A notation that describes the limiting behavior of a function when the argument tends towards a particular value/infinity.');
insert into glossary values('binary number', 'A number expressed in the base-2 numeral system.');
insert into glossary values('binary search algorithm', 'A search algorithm that finds the position of a target value within a sorted array.');
insert into glossary values('binary tree', 'A tree data structure in which each node has at most two children.');
insert into glossary values('bioinformatics', 'An interdisciplinary field that combines biology, computer science, information engineering, mathematics, and statistics.');
insert into glossary values('bit', 'A basic unit of information used in computing and digital communications.');
insert into glossary values('bit rate (R)', 'The number of bits that are conveyed or processed per unit of time.');
insert into glossary values('blacklist', 'An access control mechanism that allows through all elements, except those explicitly mentioned in a list of prohibited elements.');
insert into glossary values('BMP file format', 'A raster graphics image file format used to store bitmap digital images independently of the display device.');
insert into glossary values('Boolean data type', 'A data type that has one of two possible values (usually denoted true and false)');
insert into glossary values('Boolean expression', 'An expression used in a programming language that returns a Boolean value when evaluated.');
insert into glossary values('Boolean algebra', 'The branch of algebra in which the values of the variables are the truth values');
insert into glossary values('byte', 'A unit of digital information that most commonly consists of eight bits, representing a binary number.');
insert into glossary values('booting', 'The procedures implemented in starting up a computer or computer appliance until it can be used.');

insert into glossary values('callback', 'Any executable code that is passed as an argument to other code that is expected to execute the argument at a given time.');
insert into glossary values('central processing unit (CPU)', 'The electronic circuitry within a computer that carries out the instructions of a computer program.');
insert into glossary values('character', 'A unit of information that roughly corresponds to a grapheme, grapheme-like unit, or symbol');
insert into glossary values('cipher', 'An algorithm for performing encryption or decryption.');
insert into glossary values('class', 'An extensible program-code-template for creating objects, providing implementations of behavior');
insert into glossary values('class-based programming', 'A style of object-oriented programming which inheritance occurs via defining "classes" of objects');
insert into glossary values('client', 'A piece of computer hardware or software that accesses a service made available by a server.');
insert into glossary values('cleanroom software engineering', 'A software development process intended to produce software with a certifiable level of reliability.');
insert into glossary values('closure', 'A technique for implementing lexically scoped name binding in a language with first-class functions.');
insert into glossary values('cloud computing', 'Shared pools of configurable computer system resources that can be rapidly provisioned with minimal management effort.');
insert into glossary values('code library', 'A collection of non-volatile resources used by computer programs, often for software development.');
insert into glossary values('coding', 'The process of designing and building an executable computer program for accomplishing a specific computing task.');
insert into glossary values('coding theory', 'The study of the properties of codes and their respective fitness for specific applications.');
insert into glossary values('cognitive science', 'The interdisciplinary, scientific study of the mind and its processes.');
insert into glossary values('collection', 'Some number of data items that have some shared significance to the problem being solved');
insert into glossary values('comma-separated values (CSV)', 'A delimited text file that uses a comma to separate values.');
insert into glossary values('compiler', 'A computer program that transforms code written in one programming language into another');
insert into glossary values('computability theory', 'The study of computable functions, Turing degrees,generalized computability and definability.');
insert into glossary values('computation', 'A calculation that includes both arithmetical and non-arithmetical steps and follows a well-defined model.');
insert into glossary values('computational biology', 'Involves computational simulation techniques to the study of biological, ecological, behavioural, and social systems.');
insert into glossary values('computational chemistry', 'A branch of chemistry that uses computer simulation to assist in solving chemical problems.');
insert into glossary values('computational complexity theory', 'A subfield of computational science focusing on classifying computational problems by their difficulty');
insert into glossary values('computational model', 'A mathematical model that requires computational resources to study the behavior of a complex system by computer simulation.');
insert into glossary values('computational neuroscience', 'A branch of neuroscience employing mathematical models to understand the structure of the nervous system.');
insert into glossary values('computational physics', 'the study and implementation of numerical analysis to solve problems in physics for which a quantitative theory already exists.');
insert into glossary values('computational science', 'An interdisciplinary field that uses advanced computing capabilities to understand and solve complex problems.');
insert into glossary values('computational steering', 'Is the practice of manually intervening with an otherwise autonomous computational process, to change its outcome.');
insert into glossary values('computer', 'A device that can be instructed to carry out sequences of arithmetic or logical operations automatically via computer programming.');
insert into glossary values('computer architecture', 'A set of rules and methods that describe the functionality, organization, and implementation of computer systems.');
insert into glossary values('computer data storage', 'A technology consisting of computer components and recording media that are used to retain digital data.');
insert into glossary values('computer ethics', 'A part of practical philosophy concerned making decisions regarding professional and social conduct by IT professionals.');
insert into glossary values('computer graphics', 'Pictures and films created using computers.');
insert into glossary values('computer network', 'A digital telecommunications network which allows nodes to share resources.');
insert into glossary values('computer program', 'Is a collection of instructions that can be executed by a computer to perform a specific task.');
insert into glossary values('computer programming', 'The process of designing and building an executable computer program for accomplishing a specific computing task.');
insert into glossary values('computer science', 'The theory, experimentation, and engineering that form the basis for the design and use of computers.');
insert into glossary values('computer scientist', 'A person who has acquired the knowledge of computer science.');
insert into glossary values('computer security', 'The protection of computer systems from theft or damage to their hardware, software, or electronic data.');
insert into glossary values('computer vision', 'A scientific field that deals with computers gaining high-level understanding from digital images or videos.');
insert into glossary values('computing', 'Is any goal-oriented activity requiring, benefiting from, or creating computing machinery.');
insert into glossary values('concatenation', 'String concatenation is the operation of joining character strings end-to-end.');
insert into glossary values('concurrency', 'The ability of different parts of a program to be executed parallel, without affecting the outcome.');
insert into glossary values('conditional', 'A feature of a programming language performing different actions depending on a specified boolean');
insert into glossary values('container', 'Is a class, a data structure, or an abstract data type whose instances are collections of other objects.');
insert into glossary values('continuation-passing style (CPS)', 'A style of functional programming in which control is passed explicitly in the form of a continuation.');
insert into glossary values('control flow', 'The order in which individual statements, instructions or function calls of an imperative program are executed or evaluated.');
insert into glossary values('Creative Commons (CC)', 'A non-profit organization devoted to expanding the range of works available for others to build upon legally.');
insert into glossary values('cryptography', 'The practice and study of techniques for secure communication in the presence of third parties called adversaries.');
insert into glossary values('CSV', 'A comma-separated values (CSV) file is a delimited text file that uses a comma to separate values.');
insert into glossary values('cyberbullying', 'A form of bullying or harassment using electronic means.');
insert into glossary values('cyberspace', 'Widespread, interconnected digital technology.');

insert into glossary values('daemon', 'A computer program that runs as a background process, while being out of user control.');
insert into glossary values('data center', 'A dedicated space used to house computer systems and associated components.');
insert into glossary values('database', 'An organized collection of data, generally stored and accessed electronically from a computer system');
insert into glossary values('data mining', 'A process of discovering patterns in large data sets.');
insert into glossary values('data science', 'A field using scientific methods to extract knowledge from data in various forms');
insert into glossary values('data structure', 'A data organization, management, and storage format that enables efficient access and modification.');
insert into glossary values('data type', 'An attribute of data which tells the compiler or interpreter how the programmer intends to use the data.');
insert into glossary values('debugging', 'The process of finding and resolving defects or problems within a computer program.');
insert into glossary values('declaration', 'In programming, a language construct that specifies properties of an identifier.');
insert into glossary values('digital data', 'The discrete, discontinuous representation of information or works.');
insert into glossary values('digital signal processing (DSP)', 'The use of digital processing, to perform a wide variety of signal processing operations.');
insert into glossary values('discrete event simulation (DES)', 'A model of the operation of a system as a discrete sequence of events in time.');
insert into glossary values('disk storage', 'A general category of storage mechanisms where data is recorded.');
insert into glossary values('distributed computing', 'A field of computer science that studies distributed systems.');
insert into glossary values('divide and conquer algorithm', 'An algorithm design paradigm based on multi-branched recursion.');
insert into glossary values('documentation', 'Written text or illustration that accompanies computer software or is embedded in the source code.');
insert into glossary values('domain', 'The targeted subject area of a computer program.');
insert into glossary values('Domain Name System (DNS)', 'A hierarchical, decentralized naming system for devices connected to the Internet or to a private network.');
insert into glossary values('double-precision floating-point format', 'A computer number format representing numerical values by using a floating radix point.');
insert into glossary values('download', 'In computer networks, to receive data from a remote system, typically a server.');

insert into glossary values('edge device', 'A device which provides an entry point into enterprise or service provider core networks.');
insert into glossary values('encryption', 'In cryptography, encryption is the process of encoding information.');
insert into glossary values('event', 'An action or occurrence recognized by software, that may be handled by the software. ');
insert into glossary values('event-driven programming', 'A programming paradigm determining the program flow by events like user actions, or messages from other programs.');
insert into glossary values('evolutionary computing', 'A family of algorithms for global optimization inspired by biological evolution.');
insert into glossary values('executable', 'Causes a computer "to perform indicated tasks according to encoded instructions.');
insert into glossary values('execution', 'the process by which a computer executes the instructions of a program.');
insert into glossary values('exception handling', 'Handling the occurrence of exceptions – anomalous conditions requiring special processing');
insert into glossary values('expression', ' combination of one or more constants, variables, operators, and functions.');

insert into glossary values('fault-tolerant computer system', 'A system designed around the concept of fault tolerance.');
insert into glossary values('feasibility study', 'An investigation which aims to uncover the objective strengths and weaknesses of an existing business.');
insert into glossary values('field', 'Data that has several parts, known as a record, can be divided into fields.);
insert into glossary values('filename extension', 'An identifier specified as a suffix to the name of a computer file.');
insert into glossary values('filter (software)', 'A computer program or subroutine to process a stream, producing another stream.');
insert into glossary values('floating point arithmetic', 'Arithmetic using formulaic representation of real numbers as an approximation.');
insert into glossary values('for loop', 'A control flow statement for specifying iteration, which allows code to be executed repeatedly.');
insert into glossary values('formal methods', 'Techniques for the specification, development, and verification of software and hardware systems.');
insert into glossary values('formal verification', 'The act of proving or disproving the correctness of intended algorithms.');
insert into glossary values('functional programming', 'In programming, a style treating computation as the evaluation of mathematical functions);

insert into glossary values('game theory', 'The study of mathematical models of strategic interaction between rational decision-makers.');
insert into glossary values('garbage in, garbage out (GIGO)', 'The concept that flawed input data produces nonsense output or "garbage".');
insert into glossary values('gigabyte', 'A multiple of the unit byte for digital information. The prefix giga means 10^9.');
insert into glossary values('global variable', 'A variable that is visible and accessible throughout the program.');
insert into glossary values('graph theory', 'The study of graphs - mathematical structures used to model pairwise relations between objects.');

insert into glossary values('handle', 'An abstract reference to a resource.);
insert into glossary values('hash function', 'Any function that can be used to map data of arbitrary size to data of a fixed size.');
insert into glossary values('hash table', 'A data structure that implements an associative array abstract data type, a structure that can map keys to values.');
insert into glossary values('heap', 'A specialized tree-based data structure which is an almost complete tree that satisfies the heap property');
insert into glossary values('heapsort', 'A comparison-based sorting algorithm using a heap structure.');
insert into glossary values('human-computer interaction (HCI)', 'Researches the use of computer technology in interfaces between people and computers.');

insert into glossary values('identifier', 'algorithm design definition');
insert into glossary values('IDE', 'algorithm design definition');
insert into glossary values('imperative programming', 'algorithm design definition');
insert into glossary values('incremental build model', 'algorithm design definition');
insert into glossary values('information space analysis', 'algorithm design definition');
insert into glossary values('inheritance', 'algorithm design definition');
insert into glossary values('input/output (I/O)', 'algorithm design definition');
insert into glossary values('insertion sort', 'algorithm design definition');
insert into glossary values('instruction cycle', 'algorithm design definition');
insert into glossary values('integer', 'algorithm design definition');
insert into glossary values('integrated development environment (IDE)', 'algorithm design definition');
insert into glossary values('integration testing', 'algorithm design definition');
insert into glossary values('intellectual property (IP)', 'algorithm design definition');
insert into glossary values('intelligent agent', 'algorithm design definition');
insert into glossary values('interface', 'algorithm design definition');
insert into glossary values('internal documentation', 'algorithm design definition');
insert into glossary values('internet', 'algorithm design definition');
insert into glossary values('internet bot', 'algorithm design definition');
insert into glossary values('interpreter', 'algorithm design definition');
insert into glossary values('invariant', 'algorithm design definition');
insert into glossary values('iteration', 'algorithm design definition');

insert into glossary values('Java', 'algorithm design definition');

insert into glossary values('kernel', 'algorithm design definition');

insert into glossary values('library (computing)', 'algorithm design definition');
insert into glossary values('linear search', 'algorithm design definition');
insert into glossary values('linked list', 'algorithm design definition');
insert into glossary values('linker', 'algorithm design definition');
insert into glossary values('list', 'algorithm design definition');
insert into glossary values('loader', 'algorithm design definition');
insert into glossary values('logic error', 'algorithm design definition');
insert into glossary values('logic programming', 'algorithm design definition');

insert into glossary values('machine learning (ML)', 'algorithm design definition');
insert into glossary values('machine vision (MV)', 'algorithm design definition');
insert into glossary values('mathematical logic', 'algorithm design definition');
insert into glossary values('matrix', 'algorithm design definition');
insert into glossary values('memory', 'algorithm design definition');
insert into glossary values('merge sort', 'algorithm design definition');
insert into glossary values('method', 'algorithm design definition');
insert into glossary values('methodology', 'algorithm design definition');
insert into glossary values('modem', 'algorithm design definition');

insert into glossary values('natural language processing (NLP)', 'algorithm design definition');
insert into glossary values('node', 'algorithm design definition');
insert into glossary values('number theory', 'algorithm design definition');
insert into glossary values('numerical analysis', 'algorithm design definition');
insert into glossary values('numerical method', 'algorithm design definition');

insert into glossary values('object', 'algorithm design definition');
insert into glossary values('object code', 'algorithm design definition');
insert into glossary values('object-oriented analysis and design (OOAD)', 'algorithm design definition');
insert into glossary values('object-oriented programming (OOP)', 'algorithm design definition');
insert into glossary values('open-source software (OSS)', 'algorithm design definition');
insert into glossary values('operating system (OS)', 'algorithm design definition');
insert into glossary values('optical fiber', 'algorithm design definition');

insert into glossary values('pair programming', 'algorithm design definition');
insert into glossary values('parallel computing', 'algorithm design definition');
insert into glossary values('parameter', 'algorithm design definition');
insert into glossary values('peripheral', 'algorithm design definition');
insert into glossary values('pointer', 'algorithm design definition');
insert into glossary values('postcondition', 'algorithm design definition');
insert into glossary values('precondition', 'algorithm design definition');
insert into glossary values('primary storage', 'algorithm design definition');
insert into glossary values('priority queue', 'algorithm design definition');
insert into glossary values('primitive data type', 'algorithm design definition');
insert into glossary values('procedural programming', 'algorithm design definition');
insert into glossary values('procedure', 'algorithm design definition');
insert into glossary values('program lifecycle phase', 'algorithm design definition');
insert into glossary values('programming language', 'algorithm design definition');
insert into glossary values('programming language implementation', 'algorithm design definition');
insert into glossary values('programming language theory', 'algorithm design definition');
insert into glossary values('Prolog', 'algorithm design definition');
insert into glossary values('Python', 'algorithm design definition');

insert into glossary values('quantum computing', 'algorithm design definition');
insert into glossary values('queue', 'algorithm design definition');
insert into glossary values('quicksort', 'algorithm design definition');

insert into glossary values('R programming language', 'algorithm design definition');
insert into glossary values('radix', 'algorithm design definition');
insert into glossary values('record', 'algorithm design definition');
insert into glossary values('recursion', 'algorithm design definition');
insert into glossary values('reference', 'algorithm design definition');
insert into glossary values('reference counting', 'algorithm design definition');
insert into glossary values('relational database', 'algorithm design definition');
insert into glossary values('reliability engineering', 'algorithm design definition');
insert into glossary values('regression testing', 'algorithm design definition');
insert into glossary values('requirements analysis', 'algorithm design definition');
insert into glossary values('robotics', 'algorithm design definition');
insert into glossary values('round-off error', 'algorithm design definition');
insert into glossary values('router', 'algorithm design definition');
insert into glossary values('routing table', 'algorithm design definition');
insert into glossary values('run time', 'algorithm design definition');
insert into glossary values('run time error', 'algorithm design definition');

insert into glossary values('search algorithm', 'Any algorithm which solves the search problem, namely, to retrieve information stored within some data structure.');
insert into glossary values('secondary storage', 'Differs from primary storage in that it is not directly accessible by the CPU.');
insert into glossary values('selection sort', 'An in-place comparison sorting algorithm.');
insert into glossary values('semantics', 'The field concerned with the rigorous mathematical study of the meaning of programming languages.');
insert into glossary values('sequence', 'An enumerated collection of objects in which repetitions are allowed and order does matter.');
insert into glossary values('serializability', 'A transaction schedule is serializable if its outcome is equal to the outcome of its transactions executed serially.');
insert into glossary values('serialization', 'The process of translating data structures into a format that can be stored or transmitted and reconstructed later.');
insert into glossary values('service level agreement (SLA)', 'A commitment between a service provider and a client.');
insert into glossary values('set', 'An abstract data type that can store unique values, without any particular order.');
insert into glossary values('singleton variable', 'A variable that is referenced only once.');
insert into glossary values('software', 'A collection of data or computer instructions that tell the computer how to work.');
insert into glossary values('software agent', 'A computer program that acts for a user or other program in a relationship of agency.');
insert into glossary values('software construction', 'A software engineering discipline.');
insert into glossary values('software deployment', 'All of the activities that make a software system available for use.');
insert into glossary values('software design', 'The process by which an agent creates a specification of a software artifact using a set of primitive components and subject to constraints.');
insert into glossary values('software development', 'The process of designing, programming, documenting, testing, and bug fixing involved in creating and maintaining software components.');
insert into glossary values('software development process', 'The process of dividing software development work into distinct phases to improve design and product management.');
insert into glossary values('software engineering', 'The systematic application of engineering approaches to the development of software.');
insert into glossary values('software maintenance', 'The modification of a software product after delivery to correct faults, to improve performance or other attributes.');
insert into glossary values('software prototyping', 'The activity of creating prototypes of software applications, incomplete versions of the software program being developed.');
insert into glossary values('software requirements specification (SRS)', 'A description of a software system to be developed.');
insert into glossary values('software testing', 'An investigation conducted to provide information about the quality of the software product or service under test.');
insert into glossary values('sorting algorithm', 'An algorithm that puts elements of a list in a certain order.');
insert into glossary values('source code', 'Any collection of code, with or without comments, written using a human-readable programming language.');
insert into glossary values('spiral model', 'A risk-driven software development process model.');
insert into glossary values('stack', 'An abstract data type that serves as a collection of elements, with two main principal operations: push and pop.');
insert into glossary values('state', 'A system is described as stateful if it is designed to remember preceding events or user interactions.');
insert into glossary values('statement', 'A syntactic unit of an imperative programming language that expresses some action to be carried out.');
insert into glossary values('storage', 'A technology consisting of computer components and recording media that are used to retain digital data.');
insert into glossary values('stream', 'A sequence of data elements made available over time.');
insert into glossary values('string', 'A sequence of characters, either as a literal constant or as some kind of variable.');
insert into glossary values('structured storage', 'Provides a mechanism for storage and retrieval of data modeled in means other than the tabular relations used in relational databases.');
insert into glossary values('subroutine', 'A sequence of program instructions that performs a specific task, packaged as a unit.');
insert into glossary values('symbolic computation', 'A scientific area that refers to the study and development of algorithms and software for manipulating mathematical expressions.');
insert into glossary values('syntax', 'The set of rules that defines the combinations of symbols considered to be correctly structured statements or expressions in that language.');
insert into glossary values('syntax error', 'An error in the syntax of a sequence of characters or tokens that is intended to be written in compile-time.');
insert into glossary values('system console', 'The text entry and display device for system administration messages from the init system and from the system logger.');

insert into glossary values('technical documentation', 'Any type of documentation that describes handling, functionality, and architecture of a technical product.');
insert into glossary values('third-generation programming language (3GL)', 'A high-level computer programming language, such as ALGOL, BASIC, C, COBOL, Fortran, Java, and Pascal.');
insert into glossary values('top-down and bottom-up design', 'Strategies of information processing and knowledge ordering, used in a variety of fields.');
insert into glossary values('tree', 'A widely used abstract data type that simulates a hierarchical tree structure, with a root value and subtrees of children with a parent node.');
insert into glossary values('type theory', 'Any of a class of formal systems, some of which can serve as alternatives to set theory as a foundation for all mathematics.');

insert into glossary values('upload', 'To send data to a remote system such as a server or another client so that the remote system can store a copy.');
insert into glossary values('Uniform Resource Locator (URL)', 'A reference to a web resource that specifies its location on a computer network and a mechanism for retrieving it.');
insert into glossary values('user', 'A person who utilizes a computer or network service.');
insert into glossary values('user agent', 'Software that acts on behalf of a user, that retrieves, renders and facilitates end user interaction with some content.');
insert into glossary values('user interface (UI)', 'The space where interactions between humans and machines occur.');
insert into glossary values('user interface design', 'The design of user interfaces for machines and software with the focus on maximizing usability and the user experience.');

insert into glossary values('variable', 'A storage location paired with an associated symbolic name, which contains some known or unknown quantity of information.');
insert into glossary values('virtual machine (VM)', 'An emulation of a computer system.');
insert into glossary values('V-Model', 'A software development process that may be considered an extension of the waterfall model, and is an example of the more general V-model.');

insert into glossary values('waterfall model', 'A breakdown of project activities into linear sequential phases, where each phase depends on the deliverables of the previous one.');
insert into glossary values('Waveform Aartifactudio File Format', 'An audio file format standard, developed by Microsoft and IBM, for storing an audio bitstream on PCs.');
insert into glossary values('web crawler', 'An Internet bot that systematically browses the World Wide Web, typically for the purpose of Web indexing (web spidering).');
insert into glossary values('Wi-Fi', 'A family of wireless networking technologies, which are commonly used for local area networking of devices and Internet access.');

insert into glossary values('XHTML', 'Part of the family of XML markup languages, it mirrors or extends versions of the widely used HyperText Markup Language (HTML).');
