insert into glossary values(0, 'abstract method', 'One with only a signature and no implementation body.', -1, '0/0/0');
insert into glossary values(1, 'abstraction', 'Creating an abstract concept-object by keeping common features to various concrete objects/systems of study.', -1, '0/0/0');
insert into glossary values(2, 'agent architecture', 'A blueprint for software agents and intelligent control systems depicting the arrangement of components.', -1, '0/0/0');
insert into glossary values(3, 'agent-based model (ABM)', 'A class of computational models for simulating the actions and interactions of autonomous agents with a view to assessing the effects on the system as a whole.', -1, '0/0/0');
insert into glossary values(4, 'aggregate function', 'In database management, a function in which the values of multiple rows are grouped to form a single value, such as a sum or max.', -1, '0/0/0');
insert into glossary values(5, 'agile software development', 'An approach to software development under which and solutions evolve through self-organizing and cross-functional teams.', -1, '0/0/0');
insert into glossary values(6, 'algorithm', 'An unambiguous specification of how to solve a class of problems.', -1, '0/0/0');
insert into glossary values(7, 'algorithm design', 'A method or mathematical process for problem-solving and for engineering algorithms.', -1, '0/0/0');
insert into glossary values(8, 'algorithmic efficiency', 'A property of an algorithm which relates to the number of computational resources used by the algorithm.', -1, '0/0/0');
insert into glossary values(9, 'American Standard Code for Information Interchange (ASCII)', 'A character encoding standard for electronic communications.', -1, '0/0/0');
insert into glossary values(10, 'application programming interface (API)', 'A set of subroutine definitions, communication protocols, and tools for building software.', -1, '0/0/0');
insert into glossary values(11, 'application software', 'Computer software designed to perform a group of coordinated functions, tasks, or activities for the benefit of the user.', -1, '0/0/0');
insert into glossary values(12, 'array data structure', 'A data structure consisting of a collection of elements, each identified by at least one array index or key.', -1, '0/0/0');
insert into glossary values(13, 'artifact', 'One of many kinds of tangible by-products produced during the development of software.', -1, '0/0/0');
insert into glossary values(14, 'artificial intelligence (AI)', 'Intelligence demonstrated by machines.', -1, '0/0/0');
insert into glossary values(15, 'assertion', 'In programming, a statement that a predicate is always true at that point in code execution.', -1, '0/0/0');
insert into glossary values(16, 'associative array', 'abstract data type composed of a collection of (key, value) pairs. Each possible key appears at most once.', -1, '0/0/0');
insert into glossary values(17, 'automata theory', 'The study of abstract machines and automata, as well as the computational problems that can be solved using them.', -1, '0/0/0');
insert into glossary values(18, 'automated reasoning', 'An area of computer science and mathematical logic dedicated to understanding different aspects of reasoning.', -1, '0/0/0');
insert into glossary values(19, 'bandwidth', 'The maximum rate of data transfer across a given path.', -1, '0/0/0');
insert into glossary values(20, 'Bayesian programming', 'A technique to solve problems when less than the necessary information is available.', -1, '0/0/0');
insert into glossary values(21, 'benchmark', 'Running a computer program(s), or other operations, in order to assess the performance of an object.', -1, '0/0/0');
insert into glossary values(22, 'best, worst and average case', 'Expressions of what the resource usage is at least, at most, and on average, respectively, for a given algorithm.', -1, '0/0/0');
insert into glossary values(23, 'big data', 'Data sets that are too large or complex for traditional data-processing application software to adequately deal with.', -1, '0/0/0');
insert into glossary values(24, 'big O notation', 'A notation that describes the limiting behavior of a function when the argument tends towards a particular value/infinity.', -1, '0/0/0');
insert into glossary values(25, 'binary number', 'A number expressed in the base-2 numeral system.', -1, '0/0/0');
insert into glossary values(26, 'binary search algorithm', 'A search algorithm that finds the position of a target value within a sorted array.', -1, '0/0/0');
insert into glossary values(27, 'binary tree', 'A tree data structure in which each node has at most two children.', -1, '0/0/0');
insert into glossary values(28, 'bioinformatics', 'An interdisciplinary field that combines biology, computer science, information engineering, mathematics, and statistics.', -1, '0/0/0');
insert into glossary values(29, 'bit', 'A basic unit of information used in computing and digital communications.', -1, '0/0/0');
insert into glossary values(30, 'bit rate (R)', 'The number of bits that are conveyed or processed per unit of time.', -1, '0/0/0');
insert into glossary values(31, 'blacklist', 'An access control mechanism that allows through all elements, except those explicitly mentioned in a list of prohibited elements.', -1, '0/0/0');
insert into glossary values(32, 'BMP file format', 'A raster graphics image file format used to store bitmap digital images independently of the display device.', -1, '0/0/0');
insert into glossary values(33, 'Boolean data type', 'A data type that has one of two possible values (usually denoted true and false.', -1, '0/0/0');
insert into glossary values(34, 'Boolean expression', 'An expression used in a programming language that returns a Boolean value when evaluated.', -1, '0/0/0');
insert into glossary values(35, 'Boolean algebra', 'The branch of algebra in which the values of the variables are the truth values.', -1, '0/0/0');
insert into glossary values(36, 'byte', 'A unit of digital information that most commonly consists of eight bits, representing a binary number.', -1, '0/0/0');
insert into glossary values(37, 'booting', 'The procedures implemented in starting up a computer or computer appliance until it can be used.', -1, '0/0/0');
insert into glossary values(38, 'callback', 'Any executable code that is passed as an argument to other code that is expected to execute the argument at a given time.', -1, '0/0/0');
insert into glossary values(39, 'central processing unit (CPU)', 'The electronic circuitry within a computer that carries out the instructions of a computer program.', -1, '0/0/0');
insert into glossary values(40, 'character', 'A unit of information that roughly corresponds to a grapheme, grapheme-like unit, or symbol.', -1, '0/0/0');
insert into glossary values(41, 'cipher', 'An algorithm for performing encryption or decryption.', -1, '0/0/0');
insert into glossary values(42, 'class', 'An extensible program-code-template for creating objects, providing implementations of behavior.', -1, '0/0/0');
insert into glossary values(43, 'class-based programming', 'A style of object-oriented programming which inheritance occurs via defining "classes" of objects.', -1, '0/0/0');
insert into glossary values(44, 'client', 'A piece of computer hardware or software that accesses a service made available by a server.', -1, '0/0/0');
insert into glossary values(45, 'cleanroom software engineering', 'A software development process intended to produce software with a certifiable level of reliability.', -1, '0/0/0');
insert into glossary values(46, 'closure', 'A technique for implementing lexically scoped name binding in a language with first-class functions.', -1, '0/0/0');
insert into glossary values(47, 'cloud computing', 'Shared pools of configurable computer system resources that can be rapidly provisioned with minimal management effort.', -1, '0/0/0');
insert into glossary values(48, 'code library', 'A collection of non-volatile resources used by computer programs, often for software development.', -1, '0/0/0');
insert into glossary values(49, 'coding', 'The process of designing and building an executable computer program for accomplishing a specific computing task.', -1, '0/0/0');
insert into glossary values(50, 'coding theory', 'The study of the properties of codes and their respective fitness for specific applications.', -1, '0/0/0');
insert into glossary values(51, 'cognitive science', 'The interdisciplinary, scientific study of the mind and its processes.', -1, '0/0/0');
insert into glossary values(52, 'collection', 'Some number of data items that have some shared significance to the problem being solved.', -1, '0/0/0');
insert into glossary values(53, 'comma-separated values (CSV)', 'A delimited text file that uses a comma to separate values.', -1, '0/0/0');
insert into glossary values(54, 'compiler', 'A computer program that transforms code written in one programming language into another.', -1, '0/0/0');
insert into glossary values(55, 'computability theory', 'The study of computable functions, Turing degrees,generalized computability and definability.', -1, '0/0/0');
insert into glossary values(56, 'computation', 'A calculation that includes both arithmetical and non-arithmetical steps and follows a well-defined model.', -1, '0/0/0');
insert into glossary values(57, 'computational biology', 'Involves computational simulation techniques to the study of biological, ecological, behavioural, and social systems.', -1, '0/0/0');
insert into glossary values(58, 'computational chemistry', 'A branch of chemistry that uses computer simulation to assist in solving chemical problems.', -1, '0/0/0');
insert into glossary values(59, 'computational complexity theory', 'A subfield of computational science focusing on classifying computational problems by their difficulty.', -1, '0/0/0');
insert into glossary values(60, 'computational model', 'A mathematical model that requires computational resources to study the behavior of a complex system by computer simulation.', -1, '0/0/0');
insert into glossary values(61, 'computational neuroscience', 'A branch of neuroscience employing mathematical models to understand the structure of the nervous system.', -1, '0/0/0');
insert into glossary values(62, 'computational physics', 'the study and implementation of numerical analysis to solve problems in physics for which a quantitative theory already exists.', -1, '0/0/0');
insert into glossary values(63, 'computational science', 'An interdisciplinary field that uses advanced computing capabilities to understand and solve complex problems.', -1, '0/0/0');
insert into glossary values(64, 'computational steering', 'Is the practice of manually intervening with an otherwise autonomous computational process, to change its outcome.', -1, '0/0/0');
insert into glossary values(65, 'computer', 'A device that can be instructed to carry out sequences of arithmetic or logical operations automatically via computer programming.', -1, '0/0/0');
insert into glossary values(66, 'computer architecture', 'A set of rules and methods that describe the functionality, organization, and implementation of computer systems.', -1, '0/0/0');
insert into glossary values(67, 'computer data storage (storage, memory)', 'A technology consisting of computer components and recording media that are used to retain digital data.', -1, '0/0/0');
insert into glossary values(68, 'computer ethics', 'A part of practical philosophy concerned making decisions regarding professional and social conduct by IT professionals.', -1, '0/0/0');
insert into glossary values(69, 'computer graphics', 'Pictures and films created using computers.', -1, '0/0/0');
insert into glossary values(70, 'computer network', 'A digital telecommunications network which allows nodes to share resources.', -1, '0/0/0');
insert into glossary values(71, 'computer program', 'Is a collection of instructions that can be executed by a computer to perform a specific task.', -1, '0/0/0');
insert into glossary values(72, 'computer programming', 'The process of designing and building a computer program for accomplishing a specific computing task.', -1, '0/0/0');
insert into glossary values(73, 'computer science', 'The theory, experimentation, and engineering that form the basis for the design and use of computers.', -1, '0/0/0');
insert into glossary values(74, 'computer scientist', 'A person who has acquired the knowledge of computer science.', -1, '0/0/0');
insert into glossary values(75, 'computer security', 'The protection of computer systems from theft or damage to their hardware, software, or electronic data.', -1, '0/0/0');
insert into glossary values(76, 'computer vision', 'A scientific field that deals with computers gaining high-level understanding from digital images or videos.', -1, '0/0/0');
insert into glossary values(77, 'computing', 'Is any goal-oriented activity requiring, benefiting from, or creating computing machinery.', -1, '0/0/0');
insert into glossary values(78, 'concatenation', 'String concatenation is the operation of joining character strings end-to-end.', -1, '0/0/0');
insert into glossary values(79, 'concurrency', 'The ability of different parts of a program to be executed parallel, without affecting the outcome.', -1, '0/0/0');
insert into glossary values(80, 'conditional', 'A feature of a programming language performing different actions depending on a specified boolean.', -1, '0/0/0');
insert into glossary values(81, 'container', 'Is a class, a data structure, or an abstract data type whose instances are collections of other objects.', -1, '0/0/0');
insert into glossary values(82, 'continuation-passing style (CPS)', 'A style of functional programming in which control is passed explicitly in the form of a continuation.', -1, '0/0/0');
insert into glossary values(83, 'control flow', 'The order in which individual statements, instructions or function calls of an imperative program are executed or evaluated.', -1, '0/0/0');
insert into glossary values(84, 'Creative Commons (CC)', 'A non-profit organization devoted to expanding the range of works available for others to build upon legally.', -1, '0/0/0');
insert into glossary values(85, 'cryptography', 'The practice and study of techniques for secure communication in the presence of third parties called adversaries.', -1, '0/0/0');
insert into glossary values(86, 'CSV', 'A comma-separated values (CSV) file is a delimited text file that uses a comma to separate values.', -1, '0/0/0');
insert into glossary values(87, 'cyberbullying', 'A form of bullying or harassment using electronic means.', -1, '0/0/0');
insert into glossary values(88, 'cyberspace', 'Widespread, interconnected digital technology.', -1, '0/0/0');
insert into glossary values(89, 'daemon', 'A computer program that runs as a background process, while being out of user control.', -1, '0/0/0');
insert into glossary values(90, 'data center', 'A dedicated space used to house computer systems and associated components.', -1, '0/0/0');
insert into glossary values(91, 'database', 'An organized collection of data, generally stored and accessed electronically from a computer system.', -1, '0/0/0');
insert into glossary values(92, 'data mining', 'A process of discovering patterns in large data sets.', -1, '0/0/0');
insert into glossary values(93, 'data science', 'A field using scientific methods to extract knowledge from data in various forms.', -1, '0/0/0');
insert into glossary values(94, 'data structure', 'A data organization, management, and storage format that enables efficient access and modification.', -1, '0/0/0');
insert into glossary values(95, 'data type', 'An attribute of data which tells the compiler or interpreter how the programmer intends to use the data.', -1, '0/0/0');
insert into glossary values(96, 'debugging', 'The process of finding and resolving defects or problems within a computer program.', -1, '0/0/0');
insert into glossary values(97, 'declaration', 'In programming, a language construct that specifies properties of an identifier.', -1, '0/0/0');
insert into glossary values(98, 'digital data', 'The discrete, discontinuous representation of information or works.', -1, '0/0/0');
insert into glossary values(99, 'digital signal processing (DSP)', 'The use of digital processing, to perform a wide variety of signal processing operations.', -1, '0/0/0');
insert into glossary values(100, 'discrete event simulation (DES)', 'A model of the operation of a system as a discrete sequence of events in time.', -1, '0/0/0');
insert into glossary values(101, 'disk storage', 'A general category of storage mechanisms where data is recorded.', -1, '0/0/0');
insert into glossary values(102, 'distributed computing', 'A field of computer science that studies distributed systems.', -1, '0/0/0');
insert into glossary values(103, 'divide and conquer algorithm', 'An algorithm design paradigm based on multi-branched recursion.', -1, '0/0/0');
insert into glossary values(104, 'documentation', 'Written text or illustration that accompanies computer software or is embedded in the source code.', -1, '0/0/0');
insert into glossary values(105, 'domain', 'The targeted subject area of a computer program.', -1, '0/0/0');
insert into glossary values(106, 'Domain Name System (DNS)', 'A hierarchical, decentralized naming system for devices connected to the Internet or to a private network.', -1, '0/0/0');
insert into glossary values(107, 'double-precision floating-point format', 'A computer number format representing numerical values by using a floating radix point.', -1, '0/0/0');
insert into glossary values(108, 'download', 'In computer networks, to receive data from a remote system, typically a server.', -1, '0/0/0');
insert into glossary values(109, 'edge device', 'A device which provides an entry point into enterprise or service provider core networks.', -1, '0/0/0');
insert into glossary values(110, 'encryption', 'In cryptography, encryption is the process of encoding information.', -1, '0/0/0');
insert into glossary values(111, 'event', 'An action or occurrence recognized by software, that may be handled by the software.', -1, '0/0/0');
insert into glossary values(112, 'event-driven programming', 'A programming paradigm determining the program flow by events like user actions, or messages from other programs.', -1, '0/0/0');
insert into glossary values(113, 'evolutionary computing', 'A family of algorithms for global optimization inspired by biological evolution.', -1, '0/0/0');
insert into glossary values(114, 'executable', 'Causes a computer "to perform indicated tasks according to encoded instructions.', -1, '0/0/0');
insert into glossary values(115, 'execution', 'the process by which a computer executes the instructions of a program.', -1, '0/0/0');
insert into glossary values(116, 'exception handling', 'Handling the occurrence of exceptions – anomalous conditions requiring special processing.', -1, '0/0/0');
insert into glossary values(117, 'expression', ' combination of one or more constants, variables, operators, and functions.', -1, '0/0/0');
insert into glossary values(118, 'fault-tolerant computer system', 'A system designed around the concept of fault tolerance.', -1, '0/0/0');
insert into glossary values(119, 'feasibility study', 'An investigation which aims to uncover the objective strengths and weaknesses of an existing business.', -1, '0/0/0');
insert into glossary values(120, 'field', 'Data that has several parts, known as a record, can be divided into fields.', -1, '0/0/0');
insert into glossary values(121, 'filename extension', 'An identifier specified as a suffix to the name of a computer file.', -1, '0/0/0');
insert into glossary values(122, 'filter (software)', 'A computer program or subroutine to process a stream, producing another stream.', -1, '0/0/0');
insert into glossary values(123, 'floating point arithmetic', 'Arithmetic using formulaic representation of real numbers as an approximation.', -1, '0/0/0');
insert into glossary values(124, 'for loop', 'A control flow statement for specifying iteration, which allows code to be executed repeatedly.', -1, '0/0/0');
insert into glossary values(125, 'formal methods', 'Techniques for the specification, development, and verification of software and hardware systems.', -1, '0/0/0');
insert into glossary values(126, 'formal verification', 'The act of proving or disproving the correctness of intended algorithms.', -1, '0/0/0');
insert into glossary values(127, 'functional programming', 'In programming, a style treating computation as the evaluation of mathematical functions.', -1, '0/0/0');
insert into glossary values(128, 'game theory', 'The study of mathematical models of strategic interaction between rational decision-makers.', -1, '0/0/0');
insert into glossary values(129, 'garbage in, garbage out (GIGO)', 'The concept that flawed input data produces nonsense output or "garbage".', -1, '0/0/0');
insert into glossary values(130, 'gigabyte', 'A multiple of the unit byte for digital information. The prefix giga means 10^9.', -1, '0/0/0');
insert into glossary values(131, 'global variable', 'A variable that is visible and accessible throughout the program.', -1, '0/0/0');
insert into glossary values(132, 'graph theory', 'The study of graphs - mathematical structures used to model pairwise relations between objects.', -1, '0/0/0');
insert into glossary values(133, 'handle', 'An abstract reference to a resource.', -1, '0/0/0');
insert into glossary values(134, 'hash function', 'Any function that can be used to map data of arbitrary size to data of a fixed size.', -1, '0/0/0');
insert into glossary values(135, 'hash table', 'A data structure that implements an associative array abstract data type, a structure that can map keys to values.', -1, '0/0/0');
insert into glossary values(136, 'heap', 'A specialized tree-based data structure which is an almost complete tree that satisfies the heap property.', -1, '0/0/0');
insert into glossary values(137, 'heapsort', 'A comparison-based sorting algorithm using a heap structure.', -1, '0/0/0');
insert into glossary values(138, 'human-computer interaction (HCI)', 'Researches the use of computer technology in interfaces between people and computers.', -1, '0/0/0');
insert into glossary values(139, 'identifier', 'A token (also called a symbol) which name language entities.', -1, '0/0/0');
insert into glossary values(140, 'IDE', 'Integrated development environment.', -1, '0/0/0');
insert into glossary values(141, 'image processing', 'The use of a digital computer to process digital images through an algorithm.', -1, '0/0/0');
insert into glossary values(142, 'imperative programming', 'A programming paradigm that uses statements that change a program''s state.', -1, '0/0/0');
insert into glossary values(143, 'incremental build model', 'A method of software development where the product is designed, implemented and tested incrementally until the product is finished.', -1, '0/0/0');
insert into glossary values(144, 'information space analysis', 'A deterministic method for locating and assessing resources for team-centric efforts.', -1, '0/0/0');
insert into glossary values(145, 'information visualization', 'An interdisciplinary field that deals with the graphic representation of data and information.', -1, '0/0/0');
insert into glossary values(146, 'inheritance', 'the mechanism of basing an object or class upon another object or class, retaining similar implementation.', -1, '0/0/0');
insert into glossary values(147, 'input/output (I/O)', 'The communication between an information processing system, and the outside world.', -1, '0/0/0');
insert into glossary values(148, 'insertion sort', 'A simple sorting algorithm that builds the final sorted array one item at a time.', -1, '0/0/0');
insert into glossary values(149, 'instruction cycle', 'The cycle which the central processing unit follows from boot-up until the computer has shut down in order to process instructions.', -1, '0/0/0');
insert into glossary values(150, 'integer', 'A datum of integral data type, a data type that represents some range of mathematical integers.', -1, '0/0/0');
insert into glossary values(151, 'integrated development environment (IDE)', 'A software application that provides comprehensive facilities to computer programmers for software development.', -1, '0/0/0');
insert into glossary values(152, 'integration testing', 'The phase in software testing in which individual software modules are combined and tested as a group.', -1, '0/0/0');
insert into glossary values(153, 'intellectual property (IP)', 'A category of legal property that includes intangible creations of the human intellect.', -1, '0/0/0');
insert into glossary values(154, 'intelligent agent (IA)', 'An autonomous entity which acts upon an environment using observation through sensors and consequent actuators.', -1, '0/0/0');
insert into glossary values(155, 'interface', 'A shared boundary across which two or more separate components of a computer system exchange information.', -1, '0/0/0');
insert into glossary values(156, 'internal documentation', 'The notes on how and why various parts of code operate included within the source code as comments.', -1, '0/0/0');
insert into glossary values(157, 'internet', 'The global system of interconnected computer networks that use the Internet protocol suite to link devices worldwide.', -1, '0/0/0');
insert into glossary values(158, 'internet bot', 'A software application that runs automated tasks (scripts) over the Internet.', -1, '0/0/0');
insert into glossary values(159, 'interpreter', 'A computer program that directly executes instructions written in a programming or scripting language.', -1, '0/0/0');
insert into glossary values(160, 'invariant', 'Can be relied upon to be true during the execution of a program, or during some portion of it.', -1, '0/0/0');
insert into glossary values(161, 'iteration', 'The repetition of a process in order to generate an outcome.', -1, '0/0/0');
insert into glossary values(162, 'Java', 'A general-purpose programming language that is class-based, object-oriented and designed to have as few implementation dependencies as possible.', -1, '0/0/0');
insert into glossary values(163, 'kernel', 'The first section of an operating system to load into memory.', -1, '0/0/0');
insert into glossary values(165, 'linear search', 'A method for finding an element within a list.', -1, '0/0/0');
insert into glossary values(166, 'linked list', 'A linear collection of data elements, whose order is not given by their physical placement in memory.', -1, '0/0/0');
insert into glossary values(167, 'linker', 'A computer utility program that takes one or more object files generated by a compiler and combines them into a single executable file.', -1, '0/0/0');
insert into glossary values(168, 'list', 'An abstract data type that represents a countable number of ordered non-unique values.', -1, '0/0/0');
insert into glossary values(169, 'loader', 'The part of an operating system that is responsible for loading programs and libraries.', -1, '0/0/0');
insert into glossary values(170, 'logic error', 'A bug in a program that causes it to operate incorrectly, but not to terminate abnormally.', -1, '0/0/0');
insert into glossary values(171, 'logic programming', 'A type of programming paradigm which is largely based on formal logic.', -1, '0/0/0');
insert into glossary values(172, 'machine learning (ML)', 'The scientific study of algorithms and statistical models that computer systems use to perform a specific task without using explicit instructions.', -1, '0/0/0');
insert into glossary values(173, 'machine vision (MV)', 'The technology used to provide imaging-based automatic inspection and analysis for such applications as automatic inspection and robot guidance.', -1, '0/0/0');
insert into glossary values(174, 'mathematical logic', 'A subfield of mathematics exploring the applications of formal logic to mathematics.', -1, '0/0/0');
insert into glossary values(175, 'matrix', 'A rectangular array of numbers, symbols, or expressions, arranged in rows and columns.', -1, '0/0/0');
insert into glossary values(177, 'merge sort', 'An efficient, general-purpose, comparison-based sorting algorithm.', -1, '0/0/0');
insert into glossary values(178, 'method', 'A procedure associated with a message and an object.', -1, '0/0/0');
insert into glossary values(179, 'methodology', 'The process of dividing software development work into distinct phases to improve design, product management, and project management.', -1, '0/0/0');
insert into glossary values(180, 'modem', 'A hardware device that converts data into a format suitable for a transmission medium so that it can be transmitted from one computer to another.', -1, '0/0/0');
insert into glossary values(181, 'natural language processing (NLP)', 'A subfield of linguistics, computer science and information engineering concerned with the interactions between computers and human languages.', -1, '0/0/0');
insert into glossary values(182, 'node', 'A basic unit of a data structure, such as a linked list or tree data structure.', -1, '0/0/0');
insert into glossary values(183, 'number theory', 'A branch of pure mathematics devoted primarily to the study of the integers and integer-valued functions.', -1, '0/0/0');
insert into glossary values(184, 'numerical analysis', 'The study of algorithms that use numerical approximation for the problems of mathematical analysis.', -1, '0/0/0');
insert into glossary values(185, 'numerical method', 'A mathematical tool designed to solve numerical problems.', -1, '0/0/0');
insert into glossary values(186, 'object', 'Can be a variable, a data structure, a function, or a method, and as such, is a value in memory referenced by an identifier.', -1, '0/0/0');
insert into glossary values(187, 'object code', 'The product of a compiler.', -1, '0/0/0');
insert into glossary values(188, 'object-oriented analysis and design (OOAD)', 'A technical approach for analyzing and designing an application, system, or business by applying object-oriented programming.', -1, '0/0/0');
insert into glossary values(189, 'object-oriented programming (OOP)', 'A programming paradigm based on the concept of "objects", which can contain data, in the form of fields and code, in the form of procedures.', -1, '0/0/0');
insert into glossary values(190, 'open-source software (OSS)', 'Computer software in which source code is released under a license in which the copyright holder grants users the rights to study, change, and distribute the software.', -1, '0/0/0');
insert into glossary values(191, 'operating system (OS)', 'System software that manages computer hardware, software resources, and provides common services for computer programs.', -1, '0/0/0');
insert into glossary values(192, 'optical fiber', 'A flexible, transparent fiber made by drawing glass (silica) or plastic to a diameter slightly thicker than that of a human hair.', -1, '0/0/0');
insert into glossary values(193, 'pair programming', 'An agile software development technique in which two programmers work together at one workstation.', -1, '0/0/0');
insert into glossary values(194, 'parallel computing', 'A type of computation in which many calculations or the execution of processes are carried out simultaneously.', -1, '0/0/0');
insert into glossary values(195, 'parameter', 'A special kind of variable, used in a subroutine to refer to one of the pieces of data provided as input to the subroutine.', -1, '0/0/0');
insert into glossary values(196, 'peripheral', 'Any auxiliary or ancillary device connected to or integrated within a computer system and used to send information to or retrieve information from the computer.', -1, '0/0/0');
insert into glossary values(197, 'pointer', 'An object in many programming languages that stores a memory address.', -1, '0/0/0');
insert into glossary values(198, 'postcondition', 'A condition or predicate that must always be true just after the execution of some section of code or after an operation in a formal specification.', -1, '0/0/0');
insert into glossary values(199, 'precondition', 'A condition or predicate that must always be true just prior to the execution of some section of code or before an operation in a formal specification.', -1, '0/0/0');
insert into glossary values(200, 'primary storage', 'The only one directly accessible to the CPU.', -1, '0/0/0');
insert into glossary values(201, 'primitive data type', 'Element of a set of basic data types from which all other data types are constructed.', -1, '0/0/0');
insert into glossary values(202, 'priority queue', 'An abstract data type which is like a regular queue or stack data structure, but where additionally each element has a "priority" associated with it.', -1, '0/0/0');
insert into glossary values(203, 'procedural programming', 'A programming paradigm, derived from imperative programming, based on the concept of the procedure call.', -1, '0/0/0');
insert into glossary values(204, 'procedure', 'A subroutine.', -1, '0/0/0');
insert into glossary values(205, 'program lifecycle phase', 'One of the stages a computer program undergoes, from initial creation to deployment and execution.', -1, '0/0/0');
insert into glossary values(206, 'programming language', 'A formal language, which comprises a set of instructions that produce various kinds of output.', -1, '0/0/0');
insert into glossary values(207, 'programming language implementation', 'A system for executing computer programs.', -1, '0/0/0');
insert into glossary values(208, 'programming language theory (PLT)', 'A branch of computer science that deals with the design, implementation, analysis, characterization, and classification of programming languages.', -1, '0/0/0');
insert into glossary values(209, 'Prolog', 'A logic programming language associated with artificial intelligence and computational linguistics.', -1, '0/0/0');
insert into glossary values(210, 'Python', 'An interpreted, high-level and general-purpose programming language.', -1, '0/0/0');
insert into glossary values(211, 'quantum computing', 'The use of quantum-mechanical phenomena such as superposition and entanglement to perform computation.', -1, '0/0/0');
insert into glossary values(212, 'queue', 'A collection in which the entities in the collection are kept in order and the principal operations on the collection are the addition of entities to the rear and removal from the front.', -1, '0/0/0');
insert into glossary values(213, 'quicksort', 'An efficient sorting algorithm which serves as a systematic method for placing the elements of a random access file or an array in order.', -1, '0/0/0');
insert into glossary values(214, 'R programming language', 'A programming language and free software environment for statistical computing and graphics.', -1, '0/0/0');
insert into glossary values(215, 'radix', 'The number of unique digits, including the digit zero, used to represent numbers in a positional numeral system.', -1, '0/0/0');
insert into glossary values(216, 'record', 'A basic data structure.', -1, '0/0/0');
insert into glossary values(217, 'recursion', 'Occurs when a thing is defined in terms of itself or of its type.', -1, '0/0/0');
insert into glossary values(218, 'reference', 'A value that enables a program to indirectly access a particular datum, such as a variable''s value or a record.', -1, '0/0/0');
insert into glossary values(219, 'reference counting', 'A programming technique of storing the number of references, pointers, or handles to a resource.', -1, '0/0/0');
insert into glossary values(220, 'relational database', 'A digital database based on the relational model of data.', -1, '0/0/0');
insert into glossary values(221, 'reliability engineering', 'A sub-discipline of systems engineering that emphasizes dependability in the lifecycle management of a product.', -1, '0/0/0');
insert into glossary values(222, 'regression testing', 'Re-running functional and non-functional tests to ensure that previously developed and tested software still performs after a change.', -1, '0/0/0');
insert into glossary values(223, 'requirements analysis', 'Focuses on the tasks that determine the needs or conditions to meet the new or altered product or project.', -1, '0/0/0');
insert into glossary values(224, 'robotics', 'An interdisciplinary branch of engineering that includes mechanical, electronic and information engineering, computer science, and others.', -1, '0/0/0');
insert into glossary values(225, 'round-off error', 'The difference between the result produced by a given algorithm using exact arithmetic and the result using finite-precision, rounded arithmetic.', -1, '0/0/0');
insert into glossary values(226, 'router', 'A networking device that forwards data packets between computer networks.', -1, '0/0/0');
insert into glossary values(227, 'routing table', 'A data table stored in a router or a network host that lists the routes to particular network destinations.', -1, '0/0/0');
insert into glossary values(228, 'run time', 'The phase in which the code is being executed on the computer''s central processing unit as machine code.', -1, '0/0/0');
insert into glossary values(229, 'run time error', 'Detected after or during the execution (running state) of a program.', -1, '0/0/0');
insert into glossary values(230, 'search algorithm', 'Any algorithm which solves the search problem, namely, to retrieve information stored within some data structure.', -1, '0/0/0');
insert into glossary values(231, 'secondary storage', 'Differs from primary storage in that it is not directly accessible by the CPU.', -1, '0/0/0');
insert into glossary values(232, 'selection sort', 'An in-place comparison sorting algorithm.', -1, '0/0/0');
insert into glossary values(233, 'semantics', 'The field concerned with the rigorous mathematical study of the meaning of programming languages.', -1, '0/0/0');
insert into glossary values(234, 'sequence', 'An enumerated collection of objects in which repetitions are allowed and order does matter.', -1, '0/0/0');
insert into glossary values(235, 'serializability', 'A transaction schedule is serializable if its outcome is equal to the outcome of its transactions executed serially.', -1, '0/0/0');
insert into glossary values(236, 'serialization', 'The process of translating data structures into a format that can be stored or transmitted and reconstructed later.', -1, '0/0/0');
insert into glossary values(237, 'service level agreement (SLA)', 'A commitment between a service provider and a client.', -1, '0/0/0');
insert into glossary values(238, 'set', 'An abstract data type that can store unique values, without any particular order.', -1, '0/0/0');
insert into glossary values(239, 'singleton variable', 'A variable that is referenced only once.', -1, '0/0/0');
insert into glossary values(240, 'software', 'A collection of data or computer instructions that tell the computer how to work.', -1, '0/0/0');
insert into glossary values(241, 'software agent', 'A computer program that acts for a user or other program in a relationship of agency.', -1, '0/0/0');
insert into glossary values(242, 'software construction', 'A software engineering discipline.', -1, '0/0/0');
insert into glossary values(243, 'software deployment', 'All of the activities that make a software system available for use.', -1, '0/0/0');
insert into glossary values(244, 'software design', 'The process by which an agent creates a specification of a software artifact using a set of primitive components and subject to constraints.', -1, '0/0/0');
insert into glossary values(245, 'software development', 'The process of designing, programming, documenting, testing, and bug fixing involved in creating and maintaining software components.', -1, '0/0/0');
insert into glossary values(246, 'software development process', 'The process of dividing software development work into distinct phases to improve design and product management.', -1, '0/0/0');
insert into glossary values(247, 'software engineering', 'The systematic application of engineering approaches to the development of software.', -1, '0/0/0');
insert into glossary values(248, 'software maintenance', 'The modification of a software product after delivery to correct faults, to improve performance or other attributes.', -1, '0/0/0');
insert into glossary values(249, 'software prototyping', 'The activity of creating prototypes of software applications, incomplete versions of the software program being developed.', -1, '0/0/0');
insert into glossary values(250, 'software requirements specification (SRS)', 'A description of a software system to be developed.', -1, '0/0/0');
insert into glossary values(251, 'software testing', 'An investigation conducted to provide information about the quality of the software product or service under test.', -1, '0/0/0');
insert into glossary values(252, 'sorting algorithm', 'An algorithm that puts elements of a list in a certain order.', -1, '0/0/0');
insert into glossary values(253, 'source code', 'Any collection of code, with or without comments, written using a human-readable programming language.', -1, '0/0/0');
insert into glossary values(254, 'spiral model', 'A risk-driven software development process model.', -1, '0/0/0');
insert into glossary values(255, 'stack', 'An abstract data type that serves as a collection of elements, with two main principal operations: push and pop.', -1, '0/0/0');
insert into glossary values(256, 'state', 'A system is described as stateful if it is designed to remember preceding events or user interactions.', -1, '0/0/0');
insert into glossary values(257, 'statement', 'A syntactic unit of an imperative programming language that expresses some action to be carried out.', -1, '0/0/0');
insert into glossary values(259, 'stream', 'A sequence of data elements made available over time.', -1, '0/0/0');
insert into glossary values(260, 'string', 'A sequence of characters, either as a literal constant or as some kind of variable.', -1, '0/0/0');
insert into glossary values(261, 'structured storage', 'Provides a mechanism for storage and retrieval of data modeled in means other than the tabular relations used in relational databases.', -1, '0/0/0');
insert into glossary values(262, 'subroutine', 'A sequence of program instructions that performs a specific task, packaged as a unit.', -1, '0/0/0');
insert into glossary values(263, 'symbolic computation', 'A scientific area that refers to the study and development of algorithms and software for manipulating mathematical expressions.', -1, '0/0/0');
insert into glossary values(264, 'syntax', 'The set of rules that defines the combinations of symbols considered to be correctly structured statements or expressions in that language.', -1, '0/0/0');
insert into glossary values(265, 'syntax error', 'An error in the syntax of a sequence of characters or tokens that is intended to be written in compile-time.', -1, '0/0/0');
insert into glossary values(266, 'system console', 'The text entry and display device for system administration messages from the init system and from the system logger.', -1, '0/0/0');
insert into glossary values(267, 'technical documentation', 'Any type of documentation that describes handling, functionality, and architecture of a technical product.', -1, '0/0/0');
insert into glossary values(268, 'third-generation programming language (3GL)', 'A high-level computer programming language, such as ALGOL, BASIC, C, COBOL, Fortran, Java, and Pascal.', -1, '0/0/0');
insert into glossary values(269, 'top-down and bottom-up design', 'Strategies of information processing and knowledge ordering, used in a variety of fields.', -1, '0/0/0');
insert into glossary values(270, 'tree', 'A widely used abstract data type that simulates a hierarchical tree structure, with a root value and subtrees of children with a parent node.', -1, '0/0/0');
insert into glossary values(271, 'type theory', 'Any of a class of formal systems, some of which can serve as alternatives to set theory as a foundation for all mathematics.', -1, '0/0/0');
insert into glossary values(272, 'upload', 'To send data to a remote system such as a server or another client so that the remote system can store a copy.', -1, '0/0/0');
insert into glossary values(273, 'Uniform Resource Locator (URL)', 'A reference to a web resource that specifies its location on a computer network and a mechanism for retrieving it.', -1, '0/0/0');
insert into glossary values(274, 'user', 'A person who utilizes a computer or network service.', -1, '0/0/0');
insert into glossary values(275, 'user agent', 'Software that acts on behalf of a user, that retrieves, renders and facilitates end user interaction with some content.', -1, '0/0/0');
insert into glossary values(276, 'user interface (UI)', 'The space where interactions between humans and machines occur.', -1, '0/0/0');
insert into glossary values(277, 'user interface design', 'The design of user interfaces for machines and software with the focus on maximizing usability and the user experience.', -1, '0/0/0');
insert into glossary values(278, 'variable', 'A storage location paired with an associated symbolic name, which contains some known or unknown quantity of information.', -1, '0/0/0');
insert into glossary values(279, 'virtual machine (VM)', 'An emulation of a computer system.', -1, '0/0/0');
insert into glossary values(280, 'V-Model', 'A software development process that may be considered an extension of the waterfall model, and is an example of the more general V-model.', -1, '0/0/0');
insert into glossary values(281, 'waterfall model', 'A breakdown of project activities into linear sequential phases, where each phase depends on the deliverables of the previous one.', -1, '0/0/0');
insert into glossary values(282, 'Waveform Aartifactudio File Format', 'An audio file format standard, developed by Microsoft and IBM, for storing an audio bitstream on PCs.', -1, '0/0/0');
insert into glossary values(283, 'web crawler', 'An Internet bot that systematically browses the World Wide Web, typically for the purpose of Web indexing (web spidering).', -1, '0/0/0');
insert into glossary values(284, 'Wi-Fi', 'A family of wireless networking technologies, which are commonly used for local area networking of devices and Internet access.', -1, '0/0/0');
insert into glossary values(285, 'XHTML', 'Part of the family of XML markup languages, it mirrors or extends versions of the widely used HyperText Markup Language (HTML).', -1, '0/0/0');